ymaps.ready(init);

function init() {
	var myMap = new ymaps.Map("map", {
			center: [55.76, 37.64],
			zoom: 10
		}, {
			searchControlProvider: 'yandex#search'
		});

	var objectManager = new ymaps.ObjectManager({
		clusterize: true
	});

	objectManager.clusters.options.set("preset", "islands#invertedBlueClusterIcons");
	objectManager.clusters.options.set("clusterIconColor", "#241E0C");

	myMap.geoObjects.add(objectManager);

	// можно аяксом json подгружать
	// $.ajax({
	// 	url: "data.json"
	// }).done(function(data) {
	// 	objectManager.add(data);
	// });

	// можно json без аякса
	var data = `
		{
			"type": "FeatureCollection",
			"features": [
				{"type": "Feature", "id": 0, "geometry": {"type": "Point", "coordinates": [55.831903, 37.411961]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 0</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 0", "hintContent": "Zznak 0"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 1, "geometry": {"type": "Point", "coordinates": [55.763338, 37.565466]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 1</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 1", "hintContent": "Zznak 1"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 2, "geometry": {"type": "Point", "coordinates": [55.763338, 37.565466]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 2</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 2", "hintContent": "Zznak 2"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 3, "geometry": {"type": "Point", "coordinates": [55.744522, 37.616378]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 3</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 3", "hintContent": "Zznak 3"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 4, "geometry": {"type": "Point", "coordinates": [55.780898, 37.642889]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 4</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 4", "hintContent": "Zznak 4"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 5, "geometry": {"type": "Point", "coordinates": [55.793559, 37.435983]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 5</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 5", "hintContent": "Zznak 5"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 6, "geometry": {"type": "Point", "coordinates": [55.800584, 37.675638]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 6</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 6", "hintContent": "Zznak 6"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 7, "geometry": {"type": "Point", "coordinates": [55.716733, 37.589988]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 7</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 7", "hintContent": "Zznak 7"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 8, "geometry": {"type": "Point", "coordinates": [55.775724, 37.56084]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 8</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 8", "hintContent": "Zznak 8"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 9, "geometry": {"type": "Point", "coordinates": [55.822144, 37.433781]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 9</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 9", "hintContent": "Zznak 9"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 10, "geometry": {"type": "Point", "coordinates": [55.87417, 37.669838]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 10</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 10", "hintContent": "Zznak 10"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 11, "geometry": {"type": "Point", "coordinates": [55.71677, 37.482338]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 11</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 11", "hintContent": "Zznak 11"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 12, "geometry": {"type": "Point", "coordinates": [55.78085, 37.75021]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 12</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 12", "hintContent": "Zznak 12"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 13, "geometry": {"type": "Point", "coordinates": [55.810906, 37.654142]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 13</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 13", "hintContent": "Zznak 13"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 14, "geometry": {"type": "Point", "coordinates": [55.865386, 37.713329]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 14</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 14", "hintContent": "Zznak 14"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 15, "geometry": {"type": "Point", "coordinates": [55.847121, 37.525797]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 15</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 15", "hintContent": "Zznak 15"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 16, "geometry": {"type": "Point", "coordinates": [55.778655, 37.710743]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 16</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 16", "hintContent": "Zznak 16"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 17, "geometry": {"type": "Point", "coordinates": [55.623415, 37.717934]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 17</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 17", "hintContent": "Zznak 17"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 18, "geometry": {"type": "Point", "coordinates": [55.863193, 37.737]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 18</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 18", "hintContent": "Zznak 18"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 19, "geometry": {"type": "Point", "coordinates": [55.86677, 37.760113]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 19</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 19", "hintContent": "Zznak 19"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 20, "geometry": {"type": "Point", "coordinates": [55.698261, 37.730838]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 20</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 20", "hintContent": "Zznak 20"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 21, "geometry": {"type": "Point", "coordinates": [55.6338, 37.564769]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 21</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 21", "hintContent": "Zznak 21"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 22, "geometry": {"type": "Point", "coordinates": [55.639996, 37.5394]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 22</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 22", "hintContent": "Zznak 22"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 23, "geometry": {"type": "Point", "coordinates": [55.69023, 37.405853]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 23</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 23", "hintContent": "Zznak 23"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 24, "geometry": {"type": "Point", "coordinates": [55.77597, 37.5129]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 24</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 24", "hintContent": "Zznak 24"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 25, "geometry": {"type": "Point", "coordinates": [55.775777, 37.44218]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 25</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 25", "hintContent": "Zznak 25"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 26, "geometry": {"type": "Point", "coordinates": [55.811814, 37.440448]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 26</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 26", "hintContent": "Zznak 26"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 27, "geometry": {"type": "Point", "coordinates": [55.751841, 37.404853]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 27</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 27", "hintContent": "Zznak 27"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 28, "geometry": {"type": "Point", "coordinates": [55.627303, 37.728976]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 28</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 28", "hintContent": "Zznak 28"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 29, "geometry": {"type": "Point", "coordinates": [55.816515, 37.597163]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 29</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 29", "hintContent": "Zznak 29"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 30, "geometry": {"type": "Point", "coordinates": [55.664352, 37.689397]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 30</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 30", "hintContent": "Zznak 30"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 31, "geometry": {"type": "Point", "coordinates": [55.679195, 37.600961]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 31</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 31", "hintContent": "Zznak 31"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 32, "geometry": {"type": "Point", "coordinates": [55.673873, 37.658425]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 32</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 32", "hintContent": "Zznak 32"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 33, "geometry": {"type": "Point", "coordinates": [55.681006, 37.605126]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 33</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 33", "hintContent": "Zznak 33"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 34, "geometry": {"type": "Point", "coordinates": [55.876327, 37.431744]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 34</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 34", "hintContent": "Zznak 34"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 35, "geometry": {"type": "Point", "coordinates": [55.843363, 37.778445]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 35</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 35", "hintContent": "Zznak 35"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 36, "geometry": {"type": "Point", "coordinates": [55.875445, 37.549348]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 36</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 36", "hintContent": "Zznak 36"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 37, "geometry": {"type": "Point", "coordinates": [55.662903, 37.702087]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 37</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 37", "hintContent": "Zznak 37"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 38, "geometry": {"type": "Point", "coordinates": [55.746099, 37.434113]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 38</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 38", "hintContent": "Zznak 38"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 39, "geometry": {"type": "Point", "coordinates": [55.83866, 37.712326]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 39</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 39", "hintContent": "Zznak 39"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 40, "geometry": {"type": "Point", "coordinates": [55.774838, 37.415725]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 40</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 40", "hintContent": "Zznak 40"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 41, "geometry": {"type": "Point", "coordinates": [55.871539, 37.630223]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 41</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 41", "hintContent": "Zznak 41"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 42, "geometry": {"type": "Point", "coordinates": [55.657037, 37.571271]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 42</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 42", "hintContent": "Zznak 42"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 43, "geometry": {"type": "Point", "coordinates": [55.691046, 37.711026]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 43</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 43", "hintContent": "Zznak 43"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 44, "geometry": {"type": "Point", "coordinates": [55.803972, 37.65961]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 44</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 44", "hintContent": "Zznak 44"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 45, "geometry": {"type": "Point", "coordinates": [55.616448, 37.452759]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 45</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 45", "hintContent": "Zznak 45"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 46, "geometry": {"type": "Point", "coordinates": [55.781329, 37.442781]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 46</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 46", "hintContent": "Zznak 46"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 47, "geometry": {"type": "Point", "coordinates": [55.844708, 37.74887]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 47</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 47", "hintContent": "Zznak 47"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 48, "geometry": {"type": "Point", "coordinates": [55.723123, 37.406067]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 48</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 48", "hintContent": "Zznak 48"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}},
				{"type": "Feature", "id": 49, "geometry": {"type": "Point", "coordinates": [55.858585, 37.48498]}, "properties": {"balloonContent": "<a href='#' class='author'><div class='author__image'><div class='author__photo ibg' style='background-image: url(upload/salon/001.jpg);'></div></div><div class='author__data'><div class='author__name'>Zznak 49</div><div class='author__desc'>Татуировки</div><div class='author__rating rating'><div class='rating__points'>4,2</div><div class='rating__votes'>(25)</div></div></div></a>", "clusterCaption": "Zznak 49", "hintContent": "Zznak 49"}, "options": {"preset": "islands#circleDotIcon", "iconColor": "#DE2104", "balloonMinWidth": 300}}
			]
		}
	`;
	objectManager.add(data);

}
